### ISSUE TITLE
struct.Name vs struct.name

### ISSUE THREAD

**Issue by tschellenbach** [flosch/pongo2#156]
Great project, exactly what I was looking for. Tiny question, is there a way to have {{ struct.name }} lookup the data in {{ struct.Name }}?

**Comment by gavbaa** [comment]
Unfortunately, unexported fields are not accessible from another package in Go, and pongo2 would definitely count as another package.  Those are core language rules, and there's nothing that can be done as of 1.8 that would allow that to be worked around (they made the unexported rules even tighter).

**Comment by tschellenbach** [comment]
That makes sense, I thought it was maybe translated in the part where the variable lookup is parsed. 

Is the best approach to edit the templates and replace references of {{ user.username }} with {{ user.Username }}? (assuming user is a struct and not a map)

**Comment by gavbaa** [comment]
I misunderstood your question, you wanted to lookup to be renamed.  My apologies on that front.  I don't think that makes a lot of sense, because there's multiple lookup forms even in the normal flow (struct field, key of a map, etc.) and that would make the lookup more expensive.

Updating your template as you indicated here is the best approach I'm aware of, yes.

**Comment by tschellenbach** [comment]
Thanks for pointing me in the right direction. Much appreciated.
