### ISSUE TITLE
Get request scoped values (e. g. from pongo2.Context) in custom filter

### ISSUE THREAD

**Issue by kabukky** [flosch/pongo2#200]
Hi,

I'm currently evaluating pongo2, but can't see a solution for one of my use cases:

I certainly would want to write custom filters. Once those custom filters do network requests (maybe even concurrently) I would like to use a `context.Context`. I could easily add that to `pongo2.Context` before executing the template.

Looking at the documentation, it seems that `FilterFunction` only provides me with `Value`s, and that there is no way for me to access request scoped values (e. g. the current `pongo2.Context`). Is that right?

Is there a way I could access `pongo2.Context` or other request scoped values inside my custom filter function?

Thanks

**Comment by gavbaa** [comment]
I'm not aware of how to do it with a filter, but you could definitely do it with a tag, via the contents of the ExecutionContext.  That tends to be the line in the sand Django draws as well, filters only take the current value, tags get the whole context.

The closest you could probably get is by registering a bound method as a filter on each request with the context you want made accessible in the struct.  Clunky, and tags sound much preferable to that to me.

**Comment by kabukky** [comment]
Thanks for your fast reply and your sound explanation.

Tags are totally fine for my use case. Thanks!

I've stumbled upon the following comment in the [ExecutionContext](https://godoc.org/github.com/flosch/pongo2#ExecutionContext) documentation:

"Please be careful when accessing the Public data. PLEASE DO NOT MODIFY THE PUBLIC CONTEXT (read-only). "

What is the reason for this?

My understanding is that I would have to add my request scoped values in the public context like so:

```
var wg sync.WaitGroup
requestContext := NewContext(context.Background(), &wg)
err = tpl.ExecuteWriter(pongo2.Context{"_requestContext": &requestContext}, w)
```

If I then, as an example, want to access the `sync.WaitGroup` that I attached to the `context.Context`, I would have to access the public context using something like this:

```
func (node *testNode) Execute(ctx *pongo2.ExecutionContext, writer pongo2.TemplateWriter) *pongo2.Error {
    requestContextInterface, ok := ctx.Public["_requestContext"]
	ctx.Public
	if !ok {
		return ctx.Error("could not get requestContextInterface", nil)
	}
	requestContext, ok := requestContextInterface.(*context.Context)
	if !ok {
		return ctx.Error("requestContextInterface is not of type *context.Context", nil)
	}
    requestData, ok := FromContext(requestContext)
	if !ok {
		return nil, errors.New("Could not get *requestdata.Data from context.")
	}
    requestData.WaitGroup.Add(1)
    return nil
}
```

Would that be OK? In a way, I'm changing the public Context by adding to the `sync.WaitGroup`. But since the WaitGroup is a  Field inside the "_requestContext" value, I'm not sure it matters.

Ideally, I would add the "_requestContext" value to the `ctx.Shared` Context, but that one doesn't seem to be accessible when calling `tpl.ExecuteWriter(...)`. Is there a way to set `ctx.Shared` when executing a template?

**Comment by xc** [comment]
I was looking for some similar feature for filter and ended in here. Currently I'm using function to achieve that. But it will feel better to use filter, because sometime filer is more 'object-oriented'/natural way than eg tags/functions.

I understand filter is only for input and output anyhow, but how about debug/log info? We want to put debug/log info inside filter if something is wrong, and those info need context like request id/user information. Still hope filter can access some context info.

In my function way for example: `{{fn.get_order()}}`  will get current user's order where user id is from context.

To implement it, `fn` is registered as a variable with type map[string]func(), fn.get_order() is actually visiting fn variable's get_order member, it's just the member is a function type. (similar to [this](https://github.com/flosch/pongo2/blob/master/template_tests/function_calls_wrapper.tpl) but set context into the variable)
```
FN = struct{
   Context: context.Context
}

func (fn FN)Functions() map[string]interface{}{
    result :=map[string]interface{}{}
    result["get_order"] = func(){
       //get context from fn.Context
    }
    return result
}

variables :=map[string]interface{}{}
variables["fn"] = FN{Context: ctx}.Functions()
err := tpl.ExecuteWriter(pongo2.Context(variables), w)
```
