### ISSUE TITLE
Implement caching

### ISSUE THREAD

**Issue by ahall** [flosch/pongo2#45]
Would it make sense to have a built-in template cache which is enabled in production only (non debug)?. I can see you're currently doing this in https://github.com/macaron-contrib/pongo2/blob/master/pongo2.go where you're integrating pongo2 with a web framework. I think it would make sense to have the template cache in pongo2. Otherwise this work has to be redone when integrating with multiple frameworks which is a hassle.

Could be as simple as if the template is in cache and we're not in debug, load it from cache, otherwise reparse it.

**Comment by moadqassem** [comment]
Hello there, lately I ve been looking for a template engine which caches the templates for me, however there are no tangible results, till I came across your template engine, which in my humble opinion is the fastest and the coolest template engine, though I have note FromCache and FromFile they seem to function nearly the same from the performance perspective, and where the macros kick in and  make a difference I am afraid that the cache is not optimized in the best way or I am doing something wrong.

**Comment by flosch** [comment]
First of all: Thanks for your nice words.
pongo2 provides the `From*` functions in order to compile the template before you're using it. You would usually use these functions in order to compile all your templates at program start and then use the `*Template` instance to execute them and make pongo2 generate your template instances w.r.t your given context. 

`FromCache` is a function I implemented for convenience which you can use in your HTTP request handler (which gets executed on any request) but internally compiles a template only once. It's the same like you would pre-compile your templates first using all the other `From*` functions and then use `Execute*()` on your instances. 

So yes, there should no notably overhead (except for some internal locking when using `FromCache`). Whenever you're using `*Template` instances and you're generating them outside only once (e. g. at program start), you should always get the fastest execution speed pongo2 can provide for you.

Does this help?

**Comment by moadqassem** [comment]
Hey, Sorry for the late response, this sounds really good, what I am doing now is basically something like this:
init() { 
templatesPath := "resources/templates/mypage.html"
  mypagetmpl = pongo2.Must(pongo2.FromCache(templatesPath))
}

requesthandler() {
categoryPageTmpl.ExecuteWriter(pongo2.Context{"objects":objs}, res)
}

now I am assuming that the template should be cached somewhere, and on the next request it shouldn't recompile the template and deliver the template itself from the cache, am I correct?

**Comment by flosch** [comment]
It's correct how you're doing it. If you want to cache the result of the execution, you might want create your own cache. Caching in pongo2 means not re-compiling (and re-parsing) the whole template.

**Comment by moadqassem** [comment]
I see, yeah I am kinda working on it by not just cache the result of the execution also caching the parsed json objects(CPU caching) for better performance results, anyway thank you very much for the extra explanation :D

**Comment by flosch** [comment]
You're welcome!

**Comment by dalu** [comment]
Meanwhile SetBaseDirectory was removed for sets and I'm trying to find out what it was replaced with
