### ISSUE TITLE
Return Errors during macro execution to Execute*()-methods instead of writing them to the template.

### ISSUE THREAD

**Issue by flosch** [flosch/pongo2#54]
See title.
##

**Comment by xc** [comment]
@flosch , Is it possible to apply the fix from ProTip to master? https://github.com/HeavyHorst/pongo2/commit/8dddf7e2969fd082e6fb22fc93f23d3897a8a2d1

I have applied in v4.0.2 and looks working - only the test part failed but I ignored the test changes.

I think this feature is more and more important since so it's often that error happens. We don't want to output error in the production site... We will log it and give error message.

**Comment by HeavyHorst** [comment]
I'm happy to create a pull request with the changes.

**Comment by flosch** [comment]
Feel free to create a pull request, thanks.
