### ISSUE TITLE
Add support binary templates by go.rice

### ISSUE THREAD

**Issue by happierall** [flosch/pongo2#73]
Binary templates - fast(10x) and easy. Please add support for this.
Need changes only in the method FromFile()

Package: https://github.com/GeertJohan/go.rice

**Comment by fromYukki** [comment]
@happierall can you show some useful examples?

**Comment by happierall** [comment]
https://gist.github.com/happierall/e9d2df704f56ce575e8a

**Comment by flosch** [comment]
When using go-rice there's only a performance increase if you're calling `FromFile()` on every request (because you're avoiding all the syscalls). Usually, you're only calling `FromFile()` once on application startup (so you're only touching once the disk); pongo2 will then build an internal in-memory representation of your template for performance reasons (which will be used by any execution). There's no need to extend FromFile if you're using it right.

**Comment by happierall** [comment]
I need binary project with included templates. Because I ask for it. Please add support this. Extend doesn't work. "Base.html not found"

**Comment by flosch** [comment]
This is related to #68. You can implement your own virtual file system once this work is done.
